# Generated by Django 4.0.6 on 2024-04-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=50)),
                ('membros', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('cartaz', models.ImageField(blank=True, null=True, upload_to='cartazes')),
                ('bandas', models.ManyToManyField(to='festivais.banda')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivais.localizacao')),
            ],
        ),
    ]
