# Generated by Django 4.0.6 on 2024-04-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='descricao',
        ),
    ]
