# Generated by Django 4.0.6 on 2024-04-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='curricularIUnitReadableCode',
            new_name='curricular_unit_code',
        ),
        migrations.AddField(
            model_name='curso',
            name='area_cientifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.areacientifica'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linguagemprogramacao',
            name='projetos',
            field=models.ManyToManyField(to='curso.projeto'),
        ),
    ]
