# Generated by Django 4.0.6 on 2024-04-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_rename_curriculariunitreadablecode_disciplina_curricular_unit_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.CharField(max_length=50),
        ),
    ]
