# Generated by Django 4.0.6 on 2024-04-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_alter_disciplina_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='nome',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
