# Generated by Django 4.0.6 on 2024-03-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='number_songs',
        ),
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='band',
            name='number_members',
        ),
        migrations.RemoveField(
            model_name='band',
            name='style',
        ),
        migrations.RemoveField(
            model_name='song',
            name='time_minutes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='time_seconds',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
    ]
