# Generated by Django 4.0.6 on 2024-04-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_album_number_of_songs_album_release_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='number_of_songs',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='band',
            name='num_members',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='band',
            name='year_start',
            field=models.IntegerField(default=2024),
        ),
    ]
