# Generated by Django 4.0.6 on 2024-04-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_alter_album_number_of_songs_alter_album_release_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='0:00', max_length=10),
        ),
    ]
