# Generated by Django 4.0.6 on 2024-05-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_alter_album_cover_alter_band_bio_alter_band_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='biography',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
