# Generated by Django 4.0.6 on 2024-03-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_name',
            new_name='comenter_name',
        ),
    ]
